### ISSUE TITLE
Portable Windows builds aren't actually windows builds

### ISSUE THREAD

**Issue by crobibero** [jellyfin/jellyfin-packaging#35]
Compare contents of 10.8.9 release: https://repo.jellyfin.org/archive/server/windows/stable/10.8.9/combined/jellyfin_10.8.9.zip

to the contents of the 10.9.9 release: https://repo.jellyfin.org/files/server/windows/latest-stable/amd64/jellyfin_10.9.9-amd64.zip

**Comment by joshuaboniface** [comment]
Does 10.9.8 have the .exe? Given that the installer (persumably) works not sure how this failed.

**Comment by MarkRK** [comment]
The 10.9.8 zipfile doen not contain the jellyfin.exe.

**Comment by gnattu** [comment]
It is there from the file `https://repo.jellyfin.org/files/server/windows/latest-stable/amd64/jellyfin_10.9.9-amd64.zip`.

I guess it is something like the windows defender isolated the jellyfin.exe after unzipping.

**Comment by gnattu** [comment]
Another side note is that our current website/document is very very bad regarding the portable builds.

Because we have two kind of builds called "portable" which will confuse our users.

- The "portable" in dotnet definition of portable. Which is meant to be run with user-supplied dotnet runtime and ffmpeg
- The self-contained platform specific "portable" which is simply the tarball/zipfile of the server folder without extra packaging like making an installer or an app bundle. This one will contain ffmpeg and dotnet runtime.

The user may get confused on which to download because our document only says "portable" and the user could end up downloading the wrong one. I think we should move the portable build out of the OS section and have its own "OS" title.

**Comment by crobibero** [comment]
Ah- the actual issue is that the website doesn't link to the correct "portable" download

https://jellyfin.org/downloads/windows -> https://repo.jellyfin.org/?path=/server/portable/latest-stable

Guess the website just needs to be updated

**Comment by crobibero** [comment]
Documentation has been updated
