### ISSUE TITLE
Upgrades do not respect current state of Jellyfin service

### ISSUE THREAD

**Issue by solidsnake1298** [jellyfin/jellyfin-packaging#50]
When upgrading Jellyfin, the current state of the Jellyfin service is not respected.  My main Jellyfin is in Docker, but I maintain an apt install for testing. 
 Because of this, Jellyfin service on my server is disabled and only started for testing.  After each upgrade the service is re-enabled AND started.

**Comment by joshuaboniface** [comment]
Here's what we do right now, from `jellyfin-server.post-inst`:

```
 84 if [[ "$1" == "configure" ]] || [[ "$1" == "abort-upgrade" ]]; then
 85   if [[ -d "/run/systemd/system" ]]; then
 86     systemctl --system daemon-reload >/dev/null || true
 87     deb-systemd-invoke start jellyfin >/dev/null || true
 88   elif [[ -x "/etc/init.d/jellyfin" ]] || [[ -e "/etc/init/jellyfin.conf" ]]; then
 89     update-rc.d jellyfin defaults >/dev/null
 90     invoke-rc.d jellyfin start || exit $?
 91   fi
 92 fi
```

The problem is, we have to stop the server during `pre-inst` otherwise there's issues installing the package ("text file open" errors). But that means by the time we get to `post-inst`, we have no idea if the server was actually running or not.

I propose the following solution:

We add a `DISABLE_JELLYFIN=` flag to `/etc/default/jellyfin`, commented out by default. If this flag is uncommented, we skip this part.

Or, just mask the service until you need it. I'd prefer that option as it means we don't have to change anything.

**Comment by joshuaboniface** [comment]
Actually I will add the logic for `DISABLE_JELLYFIN`, just because i could see edge cases for it.
